### ISSUE TITLE
Cassandra schema not loaded

### ISSUE THREAD

**Issue by ledgitbe** [stoichammer/xoken-node#2]
`xoken.log` produces the following error messages: 
```
2020-02-16T17:40:29Z, E, [ERROR] produceGetDataMessage ResponseError {reHost = datacenter1:rack1:127.0.0.1:9042, reTrace = Nothing, reWarn = [], reCause = Invalid "Keyspace xoken does not exist"}
```

I'm running Cassandra with the following docker-compose:

```
version: '3.3'
services:
  cassandracompose:
    image: cassandra:3.11.5
    container_name: cassandra
    restart: always
    ports:
      #Internode communication SSL
      # - target: 7001
      #  published: 7001
      #  protocol: tcp
      #  mode: host
      #JMX
      - target: 7199
        published: 7199
        protocol: tcp
        mode: host
      #Native binary client protocol
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      #Internode communication unencrypted
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
      #Thrift protocol
      - target: 9160
        published: 9160
        protocol: tcp
        mode: host
    volumes:
      - /home/xoken/cassandra/data:/var/lib/cassandra
```
